version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '9980:3001'
    volumes:
      - /portainer/Files/AppData/Config/dashdot/:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network'
      DASHDOT_OS_LABEL_LIST: 'os,arch,up_since'
      DASHDOT_CPU_LABEL_LIST: 'brand,model,cores,threads,frequency'
      DASHDOT_STORAGE_LABEL_LIST: 'brand,size,type'
      DASHDOT_RAM_LABEL_LIST: 'brand,size,type,frequency'
      
