version: "3.8"

services:
  grafana:
      image: grafana/grafana:latest
      ports:
        - 3001:3000
      restart: unless-stopped
      volumes:
        - /portainer/Files/AppData/Config/grafana:/var/lib/grafana
        - /portainer/Files/AppData/Config/grafana/datasources:/etc/grafana/provisioning/datasources
