version: "3.9"
services:
  hauk:
    image: bilde2910/hauk:latest
    container_name: Hauk
    hostname: hauk
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 9435:80
    volumes:
      - /portainer/Files/AppData/Config/hauk:/etc/hauk:rw
    restart: on-failure:5
