version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=Europe/Athens
    ports:
      - '8945:8945'
    volumes:
      - /portainer/Files/AppData/Config/pinchflat:/config
      - /portainer/Files/AppData/Config/pinchflat/downloads:/downloads
